
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version:
* DO NOT EDIT.
*
 *
 * Copyright (C) 2015, 2016, 2017 Xilinx, Inc.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details
*

*
* Description: Driver configuration
*
*******************************************************************/


#include "xv_hdmitx.h"

/*
* The configuration table for devices
*/

XV_HdmiTx_Config XV_HdmiTx_ConfigTable[] =
{
    {
        XPAR_V_HDMI_TX_SS_0_V_HDMI_TX_DEVICE_ID,
        XPAR_V_HDMI_TX_SS_0_V_HDMI_TX_BASEADDR
    }
};
